site_name: SITES Spectral Thematic Center (SSTC) - Core

# site_description: Documentation for My Project
site_author: José M. Beltrán-Abaunza, PhD
site_url: https://github.com/SITES-spectral/sstc-core

theme:
  name: material
  # logo: images/logo.png
  # favicon: assets/favicons/SITES_favicon.png
  palette:
    primary: 'green'
    accent: 'green'
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - Tutorials:
    - Intro: tutorials/tutorials_intro.md
  - API:
      - SITES Spectral IO Tools: api_reference/sstc_core.sites.spectral.io_tools.md
      - SITES Spectral SFTP Tools: api_reference/sstc_core.sites.spectral.sftp_tools.md
      - SITES Spectral Utils: api_reference/sstc_core.sites.spectral.utils.md
      - SITES Spectral Catalog: api_reference/sstc_core.sites.spectral.catalog.md
  - Change logs: CHANGELOG.md
  - Internal docs: 
      - Acronyms construction: internal/instruments_acronyms_construcion.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_modules: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
