# Ensure you do not use hyppens "-" better to use `double__underscore`

CEM01_FOR:
  location_id: 'CEM01_FOR'
  description: 'Skogaryd Central, Mast 1'
  legacy_acronym: 'CEM01-FOR'  
  is_active: True
  mantainance_status: active
  platforms: 
    PhenoCams:
      - 'P_CEM01_FOR_1'

CEM02_FOR:
  location_id: 'CEM02_FOR'
  description: 'Skogaryd Central, Mast 2'
  legacy_acronym: 'CEM02-FOR'  
  is_active: True
  mantainance_status: active
  platforms: 
    PhenoCams:
      - 'P_CEM02_FOR_1'
CEM03_FOR:
  location_id: 'CEM03_FOR'
  description: 'Skogaryd Central, Mast 3'
  legacy_acronym: 'CEM03-FOR'  
  is_active: True
  mantainance_status: active
  platforms: 
    PhenoCams:
      - 'P_CEM03_FOR_1'
      
ERS_LAK:
  location_id: 'ERS_LAK'
  description: ''
  legacy_acronym: 'ERS-LAK'
  is_active: True
  mantainance_status: active
  platforms: 
    PhenoCams:
      - 'P_ERS-LAK_1'

#FOL_WET:
#  location_id: 'FOL_WET'
#  description: ''
#  legacy_acronym: 'FOL-WET'
#  is_active: False
#  mantainance_status: active
#  platforms: 
#    PhenoCams:
#      - 'P_FOL_WET_1'
#      - 'P_FOL_WET_2'

MAD_FOR:
  location_id: 'MAD_FOR'
  description: ''
  legacy_acronym: 'MAD-FOR'
  is_active: True
  mantainance_status: active
  platforms: 
    PhenoCams:
      - 'P_MAD_FOR_1'
      
MAD_WET:
  location_id: 'MAD_WET'
  description: ''
  legacy_acronym: 'MAD-WET'
  is_active: True
  mantainance_status: active
  platforms: 
    PhenoCams:
      - 'P_MAD_WET_1'

#STM_FOR:
#  location_id: 'STM_FOR'
#  description: ''
#  legacy_acronym: 'STM-FOR'
#  is_active: True
#  mantainance_status: active
#  platforms: 
#    PhenoCams:
#      - 'P_STM_FOR_1'