PhenoCams:
  P_SAFEA_AGR_1:
    aoi: Experimental arable land, composed by a perennial cropland system.
    backups:
      aurora02_dirpath: /home/aurora02/data/SITES/Spectral/data/catalog/lonnstorp/locations/SAFEA_AGR/platforms/PhenoCam/P_SAFEA_AGR_1/
    description: 
    ecosystem_of_interest: 
    geolocation:
      point:
          epsg: "epsg:4326"
          latitude_dd: 55.668731
          longitude_dd: 13.108632
    height_in_meters_above_ground: 10 m
    legacy_acronym: SFA-AGR
    location_id: SAFEA_AGR
    maintainance_log_filepath: '/home/aurora02/data/SITES/Spectral/code/pycode/SSTC/sstc-core/src/sstc_core/sites/spectral/maintainance/Lonnstorp-P_SAFEA_AGR_1-mantainance_log.yaml'
    status: Active
    phenocam_rois:
      ROI_01: {'points': [[], [], [], []],
        'color': [0, 255, 0],
        'thickness': 7}    
    platform_id: P_SAFEA_AGR_1
    platform_type: PhenoCam    
    sftp_dirpath: lonnstorp/data/PhenoCam/
    station_acronym: 
    station_name: Lönnstorp
    viewing_direction': west-north-west (293 degrees) and an off-nadir angle of 58 degrees.
    metadata:
      'TITLE': 'Phenocamera RGB image collection from SAFE-A, southern Sweden.'
      'SITES STATION': 'Lönnstorp Research Station'
      'TIME PERIOD': null
      'TIME RESOLUTION': 30 MINUTES
      'TIME ZONE': 'UTC+1'
      'SAMPLING POINT': 'Lönnstorp Experimental Fields, Mast 10m Phenocam 01 :  platform_id=P_SAFEA_AGR_1'
      'LATITUDE': '55.668731'
      'LONGITUDE': '13.108632'
      'ALTITUDE': '15.7 m.a.s.l'
      'FILE RETRIEVED FROM': 'https://data.fieldsites.se Link to metadata landing page is available in separate file in the downloaded zip.'
      'DATA POLICY': 'SITES data is licensed under a Creative Commons Attribution 4.0 international license (http://creativecommons.org/licenses/by/4.0/).'
      'PARAMETERS & UNITS': 'Digital Numbers (DN)'
      'DESCRIPTION': 'Collection of quality filtered phenocamera RGB images every half an hour from 10 a.m. to 2 p.m. The phenocamera pointed to an experimental arable land, composed by a perennial cropland system. For detailed information about the crop system and rotation cycle, refer to this document.'
      'SENSOR DESCRIPTION': 'Data acquired with Mobotix M25 RGB phenology camera, with wide field of view (FOV) angle of 60 degrees. Images stored in JPG format.'
      'DATA ACQUISITION': "The original images were acquired with a phenology camera on an observation mast, at a height of 10 m above ground, looking west-north-west (293 degrees) and an off-nadir angle of 58 degrees. The phenocamera acquired images from 9 a.m. to 3:30 p.m. every half an hour. The phenocamera operates all year long. The area surveyed by the phenocamera projects a footprint on the ground, the centroid of which is defined by the following coordinate (latitude, longitude in GCS WGS84, decimal degrees): 55.668731, 13.108632. "
      'PROCESSING METHODS': 
        L1_QFI: 'Data processing Level 1 Quality Filtered Images (QFI) were selected by filtered out manually from the original image collection. Individual flags were used to flag regions of interest (ROIs) that contain haze, shadows, sun glare, rain droplets, fog, or represent low-light, blurry conditions or obstacles in the image regions of interest.'
        L2_RGB_CIMV: 'Data processing level 2 Red Green Blue (RGB) Composite Image Mean Values, daily'
        L2_GCC_CIMV: 'Data processing level 2 Green Chromatic Coordinates  (GCC) Composite Image Mean Values, daily'
        L2_RCC_CIMV: 'Data processing level 2 Red Chromatic Coordinates  (RCC) Composite Image Mean Values, daily' 
        L3_ROI_TS: 'Data processing level 3 Phenocam - Green and Red Chromatic Coordinates time series of the RGB Composite Image of Mean Values - Region of Interest (ROI) Mean and Standard Deviation, daily values with QFLAG values and individual flags assesment per ROI'
      'DATA PRODUCT TYPE': 'L1_QFI'
      'DATA PRODUCT DESCRIPTION': 'Data Processing Level 1 Quality Filtered Images'
  P_SAFEA_AGR_2:
    aoi: Experimental arable land, composed by a perennial cropland system.
    backups:
      aurora02_dirpath: /home/aurora02/data/SITES/Spectral/data/catalog/lonnstorp/locations/SAFEA_AGR/platforms/PhenoCam/P_SAFEA_AGR_2/
    description: 
    ecosystem_of_interest: 
    geolocation:
      point:
          epsg: "epsg:4326"
          latitude_dd: 55.669186
          longitude_dd: 13.110360
    height_in_meters_above_ground: 10 m
    legacy_acronym: SFA-AGR
    location_id: SAFEA_AGR
    maintainance_log_filepath: '/home/aurora02/data/SITES/Spectral/code/pycode/SSTC/sstc-core/src/sstc_core/sites/spectral/maintainance/Lonnstorp-P_SAFEA_AGR_1-mantainance_log.yaml'
    status: Active
    phenocam_rois:
      ROI_01: {'points': [[], [], [], []],
        'color': [0, 255, 0],
        'thickness': 7}    
    platform_id: P_SAFEA_AGR_2
    platform_type: PhenoCam    
    sftp_dirpath: lonnstorp/data/PhenoCam/
    station_acronym: 
    station_name: Lönnstorp
    viewing_direction': Looking north (12 degrees) and an off-nadir angle of 58 degrees.
    metadata:
      'TITLE': 'Phenocamera RGB image collection from SAFE-A, southern Sweden.'
      'SITES STATION': 'Lönnstorp Research Station'
      'TIME PERIOD': null
      'TIME RESOLUTION': 30 MINUTES
      'TIME ZONE': 'UTC+1'
      'SAMPLING POINT': 'Lönnstorp Experimental Fields, Mast 10m Phenocam 02 :  platform_id=P_SAFEA_AGR_2'
      'LATITUDE': '55.668731'  # 55.669186
      'LONGITUDE': '13.108632'   # 13.110360
      'ALTITUDE': '15.7 m.a.s.l'
      'FILE RETRIEVED FROM': 'https://data.fieldsites.se Link to metadata landing page is available in separate file in the downloaded zip.'
      'DATA POLICY': 'SITES data is licensed under a Creative Commons Attribution 4.0 international license (http://creativecommons.org/licenses/by/4.0/).'
      'PARAMETERS & UNITS': 'Digital Numbers (DN)'
      'DESCRIPTION': 'Collection of quality filtered phenocamera RGB images every half an hour from 10 a.m. to 2 p.m. The phenocamera pointed to an experimental arable land, composed by a perennial cropland system. For detailed information about the crop system and rotation cycle, refer to this document.'
      'SENSOR DESCRIPTION': 'Data acquired with Mobotix M25 RGB phenology camera, with wide field of view (FOV) angle of 60 degrees. Images stored in JPG format.'
      'DATA ACQUISITION': "The original images were acquired with a phenology camera on an observation mast, at a height of 10 m above ground, looking north (12 degrees) and an off-nadir angle of 58 degrees. The phenocamera acquired images from 9 a.m. to 3:30 p.m. every half an hour. The phenocamera operates all year long. The area surveyed by the phenocamera projects a footprint on the ground, the centroid of which is defined by the following coordinate (latitude, longitude in GCS WGS84, decimal degrees): 55.669186, 13.110360."
      'PROCESSING METHODS': 
        L1_QFI: 'Data processing Level 1 Quality Filtered Images (QFI) were selected by filtered out manually from the original image collection. Individual flags were used to flag regions of interest (ROIs) that contain haze, shadows, sun glare, rain droplets, fog, or represent low-light, blurry conditions or obstacles in the image regions of interest.'
        L2_RGB_CIMV: 'Data processing level 2 Red Green Blue (RGB) Composite Image Mean Values, daily'
        L2_GCC_CIMV: 'Data processing level 2 Green Chromatic Coordinates  (GCC) Composite Image Mean Values, daily'
        L2_RCC_CIMV: 'Data processing level 2 Red Chromatic Coordinates  (RCC) Composite Image Mean Values, daily' 
        L3_ROI_TS: 'Data processing level 3 Phenocam - Green and Red Chromatic Coordinates time series of the RGB Composite Image of Mean Values - Region of Interest (ROI) Mean and Standard Deviation, daily values with QFLAG values and individual flags assesment per ROI'
      'DATA PRODUCT TYPE': 'L1_QFI'
      'DATA PRODUCT DESCRIPTION': 'Data Processing Level 1 Quality Filtered Images'
  P_SAFEA_AGR_3:
    aoi: Experimental arable land, composed by a perennial cropland system.
    backups:
      aurora02_dirpath: /home/aurora02/data/SITES/Spectral/data/catalog/lonnstorp/locations/SAFEA_AGR/platforms/PhenoCam/P_SAFEA_AGR_3/
    description: 
    ecosystem_of_interest: 
    geolocation:
      point:
          epsg: "epsg:4326"
          latitude_dd: 55.668549    # 55.669186
          longitude_dd: 13.110535   # 13.110360
    height_in_meters_above_ground: 10 m
    legacy_acronym: SFA-AGR
    location_id: SAFEA_AGR
    maintainance_log_filepath: '/home/aurora02/data/SITES/Spectral/code/pycode/SSTC/sstc-core/src/sstc_core/sites/spectral/maintainance/Lonnstorp-P_SAFEA_AGR_3-mantainance_log.yaml'
    status: Active
    phenocam_rois:
      ROI_01: {'points': [[], [], [], []],
        'color': [0, 255, 0],
        'thickness': 7}    
    platform_id: P_SAFEA_AGR_3
    platform_type: PhenoCam    
    sftp_dirpath: lonnstorp/data/PhenoCam/
    station_acronym: 
    station_name: Lönnstorp
    viewing_direction': East (85 degrees), off-nadir angle of 58 degrees.
    metadata:
      'TITLE': 'Phenocamera RGB image collection from SAFE-A, southern Sweden.'
      'SITES STATION': 'Lönnstorp Research Station'
      'TIME PERIOD': null
      'TIME RESOLUTION': 30 MINUTES
      'TIME ZONE': 'UTC+1'
      'SAMPLING POINT': 'Lönnstorp Experimental Fields, Mast 10m Phenocam 01 :  platform_id=P_SAFEA_AGR_1'
      'LATITUDE': '55.668731'
      'LONGITUDE': '13.108632'
      'ALTITUDE': '15.7 m.a.s.l'
      'FILE RETRIEVED FROM': 'https://data.fieldsites.se Link to metadata landing page is available in separate file in the downloaded zip.'
      'DATA POLICY': 'SITES data is licensed under a Creative Commons Attribution 4.0 international license (http://creativecommons.org/licenses/by/4.0/).'
      'PARAMETERS & UNITS': 'Digital Numbers (DN)'
      'DESCRIPTION': 'Collection of quality filtered phenocamera RGB images every half an hour from 10 a.m. to 2 p.m. The phenocamera pointed to an experimental arable land, composed by a perennial cropland system. For detailed information about the crop system and rotation cycle, refer to this document.'
      'SENSOR DESCRIPTION': 'Data acquired with Mobotix M25 RGB phenology camera, with wide field of view (FOV) angle of 60 degrees. Images stored in JPG format.'
      'DATA ACQUISITION': "The original images were acquired with a phenology camera on an observation mast, at a height of 10 m above ground, looking east (85 degrees) and an off-nadir angle of 58 degrees. The phenocamera acquired images from 9 a.m. to 3:30 p.m. every half an hour. The phenocamera operates all year long. The area surveyed by the phenocamera projects a footprint on the ground, the centroid of which is defined by the following coordinate (latitude, longitude in GCS WGS84, decimal degrees): 55.668549, 13.110535."
      'PROCESSING METHODS': 
        L1_QFI: 'Data processing Level 1 Quality Filtered Images (QFI) were selected by filtered out manually from the original image collection. Individual flags were used to flag regions of interest (ROIs) that contain haze, shadows, sun glare, rain droplets, fog, or represent low-light, blurry conditions or obstacles in the image regions of interest.'
        L2_RGB_CIMV: 'Data processing level 2 Red Green Blue (RGB) Composite Image Mean Values, daily'
        L2_GCC_CIMV: 'Data processing level 2 Green Chromatic Coordinates  (GCC) Composite Image Mean Values, daily'
        L2_RCC_CIMV: 'Data processing level 2 Red Chromatic Coordinates  (RCC) Composite Image Mean Values, daily' 
        L3_ROI_TS: 'Data processing level 3 Phenocam - Green and Red Chromatic Coordinates time series of the RGB Composite Image of Mean Values - Region of Interest (ROI) Mean and Standard Deviation, daily values with QFLAG values and individual flags assesment per ROI'
      'DATA PRODUCT TYPE': 'L1_QFI'
      'DATA PRODUCT DESCRIPTION': 'Data Processing Level 1 Quality Filtered Images'
       