PhenoCams:
  P_CEM01_FOR_1:
    aoi: Skogaryd Central, western Sweden
    backups:
      aurora02_dirpath: /home/aurora02/data/SITES/Spectral/data/catalog/skogaryd/locations/SKC_FOR/platforms/PhenoCam/P_CEM01_FOR_1/
    description: spruce forest
    ecosystem_of_interest: FOR
    geolocation:
      point:
          epsg: "epsg:4326"
          latitude_dd: 58.363058
          longitude_dd: 12.14965
    height_in_meters_above_ground: 38 m
    legacy_acronym: CEM01-FOR-P01
    location_id: CEM01_FOR
    maintainance_log_filepath: '/home/aurora02/data/SITES/Spectral/code/pycode/SSTC/sstc-core/src/sstc_core/sites/spectral/maintainance/Skogaryd-P_CEM01_FOR_1-mantainance_log.yaml'
    status: Active
    phenocam_rois:
      ROI_01: {'points': [[300, 1800], [300, 400], [2700, 400], [2700, 1200], [2400, 1400], [2200, 1800]],
        'color': [0, 255, 0],
        'thickness': 7}
      ROI_02: {'points': [[2600, 1950], [2600, 1680], [2950, 1680], [2950, 1950]],
        'color': [0, 0, 255],
        'thickness': 7}    
    platform_id: P_CEM01_FOR_1
    platform_type: PhenoCam    
    sftp_dirpath: /skogaryd/data/PhenoCam/CEM01-FOR-P01
    station_acronym: SKC
    station_name: Skogaryd
    viewing_direction': south (185 degrees) and an off-nadir angle of 38 degrees
    metadata:
      'TITLE': ''
      'SITES STATION': 'Skogaryd Research Catchment'
      'TIME PERIOD': null
      'TIME RESOLUTION': HOURLY
      'TIME ZONE': 'UTC+1'
      'SAMPLING POINT': 'Skogaryd Central, Mast 1 Phenocam 01 :  platform_id=P_CEM01_FOR_1'
      'LATITUDE': '58.363058'
      'LONGITUDE': '12.14965'
      'ALTITUDE': '76.4 m.a.s.l'
      'FILE RETRIEVED FROM': 'https://data.fieldsites.se Link to metadata landing page is available in separate file in the downloaded zip.'
      'DATA POLICY': 'SITES data is licensed under a Creative Commons Attribution 4.0 international license (http://creativecommons.org/licenses/by/4.0/).'
      'PARAMETERS & UNITS': 'Digital Numbers (DN)'
      'DESCRIPTION': 'Collection of quality filtered phenocamera RGB images every half an hour from 10:00 to 14:30 UTC+1. The phenocamera pointed to a grown spruce forest (Picea abies), with tree heights of 30 m, approximately.'
      'SENSOR DESCRIPTION': 'Data acquired with Mobotix M25 RGB phenology camera, with wide field of view (FOV) angle of 60 degrees. Images stored in JPG format.'
      'DATA ACQUISITION': "The original images were acquired with phenology camera on an observation mast, at a height of 38 m above ground, looking south (185 degrees) and an off-nadir angle of 38 degrees. The phenocamera acquired images from 4 a.m. to 8 p.m. every hour. The phenocamera operates all year long. The area surveyed by the phenocamera projects a footprint on the ground, the centroid of which is defined by the following coordinate (latitude, longitude in GCS WGS84, decimal degrees): 58.363058, 12.14965."
      'PROCESSING METHODS': 
        L1_QFI: 'Data processing Level 1 Quality Filtered Images (QFI) were selected by filtered out manually from the original image collection. Individual flags were used to flag regions of interest (ROIs) that contain haze, shadows, sun glare, rain droplets, fog, or represent low-light, blurry conditions or obstacles in the image regions of interest.'
        L2_RGB_CIMV: 'Data processing level 2 Red Green Blue (RGB) Composite Image Mean Values, daily'
        L2_GCC_CIMV: 'Data processing level 2 Green Chromatic Coordinates  (GCC) Composite Image Mean Values, daily'
        L2_RCC_CIMV: 'Data processing level 2 Red Chromatic Coordinates  (RCC) Composite Image Mean Values, daily' 
        L3_ROI_TS: 'Data processing level 3 Phenocam - Green and Red Chromatic Coordinates time series of the RGB Composite Image of Mean Values - Region of Interest (ROI) Mean and Standard Deviation, daily values with QFLAG values and individual flags assesment per ROI'
      'DATA PRODUCT TYPE': 'L1_QFI'
      'DATA PRODUCT DESCRIPTION': 'Data Processing Level 1 Quality Filtered Images'
  P_CEM02_FOR_1:
    aoi: Skogaryd Central, western Sweden
    backups:
      aurora02_dirpath: /home/aurora02/data/SITES/Spectral/data/catalog/skogaryd/locations/SKC_FOR/platforms/PhenoCam/P_CEM02_FOR_1/
    description: understory of a spruce forest
    ecosystem_of_interest: FOR
    geolocation:
      point:
          epsg: "epsg:4326"
          latitude_dd: 58.363718
          longitude_dd: 12.149323
    height_in_meters_above_ground: 3 m
    legacy_acronym: CEM02-FOR-P02
    location_id: CEM02_FOR
    maintainance_log_filepath: '/home/aurora02/data/SITES/Spectral/code/pycode/SSTC/sstc-core/src/sstc_core/sites/spectral/maintainance/Skogaryd-P_CEM02_FOR_1-mantainance_log.yaml'
    status: Active
    phenocam_rois:
      ROI_01: {'points': [[2550, 700], [2550, 1850], [700, 1850], [700, 700]],
        'color': [0, 255, 0],
        'thickness': 7}      
    platform_id: P_CEM02_FOR_1
    platform_type: PhenoCam    
    sftp_dirpath: /skogaryd/data/PhenoCam/CEM02-FOR-P02
    station_acronym: SKC
    station_name: Skogaryd
    viewing_direction': west (270 degrees) and an off-nadir angle of 47 degrees
    metadata:
      'TITLE': ''
      'SITES STATION': 'Skogaryd Research Catchment'
      'TIME PERIOD': null
      'TIME RESOLUTION': HOURLY
      'TIME ZONE': 'UTC+1'
      'SAMPLING POINT': 'Skogaryd Central, Mast 2 Phenocam 01 :  platform_id=P_CEM02_FOR_1'
      'LATITUDE': '58.363718'
      'LONGITUDE': '12.149323'
      'ALTITUDE': '76.5 m.a.s.l'
      'FILE RETRIEVED FROM': 'https://data.fieldsites.se Link to metadata landing page is available in separate file in the downloaded zip.'
      'DATA POLICY': 'SITES data is licensed under a Creative Commons Attribution 4.0 international license (http://creativecommons.org/licenses/by/4.0/).'
      'PARAMETERS & UNITS': 'Digital Numbers (DN)'
      'DESCRIPTION': 'Collection of quality filtered phenocamera RGB images every half an hour from 10:00 to 14:30 UTC+1. The phenocamera pointed to the understory of a spruce forest (Picea abies) composed by a floor of the perennial glittering wood moss (Hylocomium splendens) with hints of common wood sorrel (Oxalis acetosella).'
      'SENSOR DESCRIPTION': 'Data acquired with Mobotix M25 RGB phenology camera, with wide field of view (FOV) angle of 60 degrees. Images stored in JPG format.'
      'DATA ACQUISITION': "The original images were acquired with phenology camera on an observation mast, at a height of 3 m above ground, looking west (270 degrees) and an off-nadir angle of 47 degrees. The phenocamera acquired images from 4 a.m. to 8 p.m. every hour. The phenocamera operates all year long. The area surveyed by the phenocamera projects a footprint on the ground, the centroid of which is defined by the following coordinate (latitude, longitude in GCS WGS84, decimal degrees): 58.363718, 12.149323."
      'PROCESSING METHODS': 
        L1_QFI: 'Data processing Level 1 Quality Filtered Images (QFI) were selected by filtered out manually from the original image collection. Individual flags were used to flag regions of interest (ROIs) that contain haze, shadows, sun glare, rain droplets, fog, or represent low-light, blurry conditions or obstacles in the image regions of interest.'
        L2_RGB_CIMV: 'Data processing level 2 Red Green Blue (RGB) Composite Image Mean Values, daily'
        L2_GCC_CIMV: 'Data processing level 2 Green Chromatic Coordinates  (GCC) Composite Image Mean Values, daily'
        L2_RCC_CIMV: 'Data processing level 2 Red Chromatic Coordinates  (RCC) Composite Image Mean Values, daily' 
        L3_ROI_TS: 'Data processing level 3 Phenocam - Green and Red Chromatic Coordinates time series of the RGB Composite Image of Mean Values - Region of Interest (ROI) Mean and Standard Deviation, daily values with QFLAG values and individual flags assesment per ROI'
      'DATA PRODUCT TYPE': 'L1_QFI'
      'DATA PRODUCT DESCRIPTION': 'Data Processing Level 1 Quality Filtered Images'
  P_CEM03_FOR_1:
    aoi: Skogaryd Central, western Sweden
    backups:
      aurora02_dirpath: /home/aurora02/data/SITES/Spectral/data/catalog/skogaryd/locations/SKC_FOR/platforms/PhenoCam/P_CEM03_FOR_1/
    description: mature spruce forest with a few species of grasses and herbaceous plants
    ecosystem_of_interest: FOR
    geolocation:
      point:
          epsg: "epsg:4326"
          latitude_dd: 58.363555
          longitude_dd: 12.149786
    height_in_meters_above_ground: 3 m
    legacy_acronym: CEM03-FOR-P03
    location_id: CEM03_FOR
    maintainance_log_filepath: '/home/aurora02/data/SITES/Spectral/code/pycode/SSTC/sstc-core/src/sstc_core/sites/spectral/maintainance/Skogaryd-P_CEM03_FOR_1-mantainance_log.yaml'
    status: Active
    phenocam_rois:
      ROI_01: {'points': [[500, 500], [2500, 500], [2500, 1750], [500,1750]],
        'color': [0, 255, 0],
        'thickness': 7}      
    platform_id: P_CEM03_FOR_1
    platform_type: PhenoCam    
    sftp_dirpath: /skogaryd/data/PhenoCam/CEM03-FOR-P03
    station_acronym: SKC
    station_name: Skogaryd
    viewing_direction': west (270 degrees) and an off-nadir angle of 42 degrees
    metadata:
      'TITLE': ''
      'SITES STATION': 'Skogaryd Research Catchment'
      'TIME PERIOD': null
      'TIME RESOLUTION': HOURLY
      'TIME ZONE': 'UTC+1'
      'SAMPLING POINT': 'Skogaryd Central, Mast 3 Phenocam 01 :  platform_id=P_CEM03_FOR_1'
      'LATITUDE': '58.363555'
      'LONGITUDE': '12.149786'
      'ALTITUDE': '76.2 m.a.s.l'
      'FILE RETRIEVED FROM': 'https://data.fieldsites.se Link to metadata landing page is available in separate file in the downloaded zip.'
      'DATA POLICY': 'SITES data is licensed under a Creative Commons Attribution 4.0 international license (http://creativecommons.org/licenses/by/4.0/).'
      'PARAMETERS & UNITS': 'Digital Numbers (DN)'
      'DESCRIPTION': 'Collection of quality filtered phenocamera RGB images every half an hour from 10:00 to 14:30 UTC+1. The phenocamera pointed to an opening in the mature spruce forest with a few species of grasses and herbaceous plants, among others, wood horsetail (Equisetum sylvaticum), creeping bentgrass (Agrostis stolonifera) and common wood sorrel (Oxalis acetosella), on a floor of glittering wood moss (Hylocomium splendens) with some Polytrichum spp and red-stemmed feathermoss (Pleurozium schreberi).'
      'SENSOR DESCRIPTION': 'Data acquired with Mobotix M25 RGB phenology camera, with wide field of view (FOV) angle of 60 degrees. Images stored in JPG format.'
      'DATA ACQUISITION': "The original images were acquired with phenology camera on an observation mast, at a height of 3 m above ground, looking west (270 degrees) and an off-nadir angle of 42 degrees. The phenocamera acquired images from 4 a.m. to 8 p.m. every hour. The phenocamera operates all year long. The area surveyed by the phenocamera projects a footprint on the ground, the centroid of which is defined by the following coordinate (latitude, longitude in GCS WGS84, decimal degrees): 58.363555, 12.149786."
      'PROCESSING METHODS': 
        L1_QFI: 'Data processing Level 1 Quality Filtered Images (QFI) were selected by filtered out manually from the original image collection. Individual flags were used to flag regions of interest (ROIs) that contain haze, shadows, sun glare, rain droplets, fog, or represent low-light, blurry conditions or obstacles in the image regions of interest.'
        L2_RGB_CIMV: 'Data processing level 2 Red Green Blue (RGB) Composite Image Mean Values, daily'
        L2_GCC_CIMV: 'Data processing level 2 Green Chromatic Coordinates  (GCC) Composite Image Mean Values, daily'
        L2_RCC_CIMV: 'Data processing level 2 Red Chromatic Coordinates  (RCC) Composite Image Mean Values, daily' 
        L3_ROI_TS: 'Data processing level 3 Phenocam - Green and Red Chromatic Coordinates time series of the RGB Composite Image of Mean Values - Region of Interest (ROI) Mean and Standard Deviation, daily values with QFLAG values and individual flags assesment per ROI'
      'DATA PRODUCT TYPE': 'L1_QFI'
      'DATA PRODUCT DESCRIPTION': 'Data Processing Level 1 Quality Filtered Images'